kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Port 80 on localhost will map to port 80 in the cluster (for HTTP traffic)
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # Port 443 for HTTPS
  - containerPort: 443
    hostPort: 443
    protocol: TCP
